// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEXCHAT.Plugin.EFCore;

#nullable disable

namespace NEXCHAT.Infrastructure.Migrations
{
    [DbContext(typeof(NEXCHATDBContext))]
    partial class NEXCHATDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111155",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111166",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateStartedUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupCoverPhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGroupConversation")
                        .HasColumnType("bit");

                    b.HasKey("ConversationId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.ConversationParticipant", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.ConversationTypingUser", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationTypingUsers");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateSentUTC")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.MessageReaction", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserReactedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageReactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageId", "UserReactedId");

                    b.HasIndex("MessageId");

                    b.HasIndex("ReactionId");

                    b.HasIndex("UserReactedId");

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.MessageSeen", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SeenAtUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessagesSeen");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Reaction", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmojiPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReactionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReactionId");

                    b.HasIndex("ReactionName")
                        .IsUnique();

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111114"),
                            EmojiPath = "https://lottie.host/91d7a732-3fef-4397-a427-dfc9ce7513fd/vhgRnJQiUz.lottie",
                            ReactionName = "Laughing"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111115"),
                            EmojiPath = "https://lottie.host/861562a2-2975-4b7a-847a-f50431be25f0/D6hWtQp9EM.lottie",
                            ReactionName = "Sad"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111116"),
                            EmojiPath = "https://lottie.host/9ef73a79-293c-496c-82f7-ed27c40d63eb/RGg5Ewhxx3.lottie",
                            ReactionName = "Angel"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111117"),
                            EmojiPath = "https://lottie.host/30a2c4c6-0277-4b7d-8d85-f8fd6ddbdb88/Zg2ds75R2E.lottie",
                            ReactionName = "Kiss"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111118"),
                            EmojiPath = "https://lottie.host/5bda14b0-e838-4074-bb58-e85f6608db6d/ovIILqAs4u.lottie",
                            ReactionName = "Dissapointed"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111119"),
                            EmojiPath = "https://lottie.host/a4cff48f-156f-4114-b27e-cff7bd0f29a6/hE5NQSPEyA.lottie",
                            ReactionName = "Angry"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111100"),
                            EmojiPath = "https://lottie.host/76e83562-9204-4362-9fcc-60a17e219d40/nrBKNNLnfZ.lottie",
                            ReactionName = "Unhappy"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111122"),
                            EmojiPath = "https://lottie.host/29d5ff89-287f-42d1-89bc-25b695e2ed7f/hZFip2GqwA.lottie",
                            ReactionName = "Suprised"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111133"),
                            EmojiPath = "https://lottie.host/632a0f85-69e8-4b70-8d67-02c1c2e08365/XJNJAOQu8D.lottie",
                            ReactionName = "Cool"
                        },
                        new
                        {
                            ReactionId = new Guid("11111111-1111-1111-1111-111111111144"),
                            EmojiPath = "https://lottie.host/1ba46ee9-b4d2-44c7-baa8-8fa0adc4ccb7/oc0HMXijhA.lottie",
                            ReactionName = "Crying"
                        });
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Bio = "Aspiring writer and tech innovator...",
                            Country = "United States",
                            DateJoined = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "proxima@gmail.com",
                            FirstName = "Proxima",
                            LastLogin = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Cen",
                            PasswordHash = "AQAAAAIAAYagAAAAEBWuvAH8bLsGDStNP11zDw42A3H2kcA+T0dYM/sVp1D2nS+hIy/85ADCgN9ShVURVw==",
                            Phone = "1234567890",
                            PhotoPath = "Uploads/User/bettle.jpg",
                            Roles = "[\"User\"]",
                            SecurityAnswer = "Jessie",
                            SecurityQuestion = "What was the name of your first pet?",
                            Status = "Online",
                            UserName = "proximacen10"
                        },
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Bio = "Night sky enthusiast and telescope collector",
                            Country = "Canada",
                            DateJoined = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "astro@example.com",
                            FirstName = "Orion",
                            LastLogin = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Starborn",
                            PasswordHash = "AQAAAAIAAYagAAAAEBWuvAH8bLsGDStNP11zDw42A3H2kcA+T0dYM/sVp1D2nS+hIy/85ADCgN9ShVURVw==",
                            Phone = "555-1234",
                            PhotoPath = "Uploads/User/orion.jpg",
                            Roles = "[\"User\"]",
                            SecurityAnswer = "Jessie",
                            SecurityQuestion = "What was the name of your first pet?",
                            Status = "Offline",
                            UserName = "astro_photographer"
                        },
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111113"),
                            Bio = "Building the future of communication technology",
                            Country = "United Kingdom",
                            DateJoined = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pioneer@tech.io",
                            FirstName = "Ada",
                            LastLogin = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Innovator",
                            PasswordHash = "AQAAAAIAAYagAAAAEBWuvAH8bLsGDStNP11zDw42A3H2kcA+T0dYM/sVp1D2nS+hIy/85ADCgN9ShVURVw==",
                            Phone = "+1-555-9876",
                            PhotoPath = "Uploads/User/ada.jpg",
                            Roles = "[\"User\"]",
                            SecurityAnswer = "Jessie",
                            SecurityQuestion = "What was the name of your first pet?",
                            Status = "Offline",
                            UserName = "tech_pioneer"
                        });
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.UserFriend", b =>
                {
                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RequesterId", "ReceiverId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("RequesterId");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Conversation", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.ConversationParticipant", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.ConversationTypingUser", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.Conversation", "Conversation")
                        .WithMany("ParticipantsTyping")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Message", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.MessageReaction", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.Reaction", "Reaction")
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.User", "UserReadcted")
                        .WithMany()
                        .HasForeignKey("UserReactedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Reaction");

                    b.Navigation("UserReadcted");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.MessageSeen", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.Message", "Message")
                        .WithMany("SeenBy")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Notification", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.UserFriend", b =>
                {
                    b.HasOne("NEXCHAT.CoreBusiness.User", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NEXCHAT.CoreBusiness.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");

                    b.Navigation("ParticipantsTyping");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.Message", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("SeenBy");
                });

            modelBuilder.Entity("NEXCHAT.CoreBusiness.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
